# Generated by Django 4.1.1 on 2022-10-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified_at",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "price",
                    models.PositiveIntegerField(default=0, verbose_name="Precio"),
                ),
            ],
            options={
                "verbose_name": "Fare",
                "verbose_name_plural": "Fares",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified_at",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                ("name", models.CharField(max_length=3, verbose_name="Numero")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("av", "Disponible"),
                            ("bu", "Ocupado"),
                            ("re", "Reservado"),
                            ("ma", "Mantenimiento"),
                        ],
                        max_length=2,
                        verbose_name="Estado Estacionamiento",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("no", "Normal"), ("di", "Discapacitado")],
                        max_length=2,
                        verbose_name="Tipo Estacionamiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot",
                "verbose_name_plural": "Lots",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Reserve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified_at",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("bu", "Ocupada"),
                            ("fi", "Terminada"),
                            ("pp", "Pago Pendiente"),
                            ("ma", "Anulada"),
                        ],
                        default="bu",
                        max_length=2,
                        verbose_name="Estado de Reserva",
                    ),
                ),
                ("licence", models.CharField(max_length=15, verbose_name="Patente")),
                (
                    "check_in",
                    models.DateTimeField(auto_now_add=True, verbose_name="Entrada"),
                ),
                (
                    "check_out",
                    models.DateTimeField(blank=True, null=True, verbose_name="Salida"),
                ),
                (
                    "fare",
                    models.ForeignKey(
                        default="normal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserves",
                        to="reserves.fare",
                        verbose_name="Tarifa",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserves",
                        to="reserves.lot",
                        verbose_name="Estacionamiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserve",
                "verbose_name_plural": "Reserves",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified_at",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                ("obs", models.TextField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ca", "Cancelado"),
                            ("an", "Anulado"),
                            ("re", "Revisado"),
                        ],
                        default="ca",
                        max_length=2,
                    ),
                ),
                (
                    "reserve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="reserves.reserve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["id"],
            },
        ),
    ]
