# Generated by Django 4.1.1 on 2022-10-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserves", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserve",
            name="status",
            field=models.CharField(
                choices=[
                    ("bu", "Ocupada"),
                    ("fi", "Terminada"),
                    ("pp", "Pago Pendiente"),
                    ("an", "Anulada"),
                ],
                default="bu",
                max_length=2,
                verbose_name="Estado de Reserva",
            ),
        ),
    ]
