# Generated by Django 4.1.1 on 2022-10-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserves", "0002_alter_reserve_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="obs",),
        migrations.AddField(
            model_name="reserve",
            name="obs",
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
