# Generated by Django 4.1.1 on 2022-10-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserves", "0003_remove_payment_obs_reserve_obs"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="status",),
        migrations.AlterField(
            model_name="reserve",
            name="status",
            field=models.CharField(
                choices=[("bu", "Ocupada"), ("fi", "Terminada"), ("an", "Anulada")],
                default="bu",
                max_length=2,
                verbose_name="Estado de Reserva",
            ),
        ),
    ]
