# Generated by Django 4.1.1 on 2022-10-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserves", "0007_rename_fareplan_fareperiod_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserveperiod",
            name="total",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reserveperiod",
            name="status",
            field=models.CharField(
                choices=[("in", "Iniciada"), ("fi", "Finalizada"), ("an", "Anulada")],
                default="in",
                max_length=2,
                verbose_name="Estado de Reserva Periodo",
            ),
        ),
    ]
