# Generated by Django 4.1.1 on 2022-10-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserves", "0008_reserveperiod_total_alter_reserveperiod_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="Apellido"),
                ),
                (
                    "document_number",
                    models.CharField(max_length=50, verbose_name="Numero de Documento"),
                ),
                (
                    "social_reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Razón Social"
                    ),
                ),
                ("adress", models.CharField(max_length=250, verbose_name="Dirección")),
                ("phone", models.CharField(max_length=50, verbose_name="Telefóno")),
                ("email", models.EmailField(max_length=254, verbose_name="Correo")),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["id"],
            },
        ),
    ]
