# Generated by Django 4.1.1 on 2022-11-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserves", "0010_reserveperiod_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="status",
            field=models.CharField(
                choices=[
                    ("av", "Disponible"),
                    ("bu", "Ocupado"),
                    ("re", "Reservado"),
                    ("ma", "Mantenimiento"),
                ],
                default="av",
                max_length=2,
                verbose_name="Estado Estacionamiento",
            ),
        ),
        migrations.AlterField(
            model_name="reserveperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("re", "Reservada"),
                    ("in", "Iniciada"),
                    ("fi", "Finalizada"),
                    ("an", "Anulada"),
                ],
                default="in",
                max_length=2,
                verbose_name="Estado de Reserva Periodo",
            ),
        ),
    ]
